# 실험 설정
experiment_id: resnet_colormap_v1
backbone_name: EfficientNetB0 #ResNet50 MobileNetV2 DenseNet121 EfficientNetB0

# 데이터셋 설정
original_dataset_dir: /Volumes/PortableSSD/data
base_output_dir: /Users/vnlt/PROJECT/ex-cnn-cv/data/dataset
input_shape: [224, 224, 3]
train_ratio: 0.7 
val_ratio: 0.2 
test_ratio: 0.1
seed: 42
augmentations:
  #- color_jitter:
      # brightness: 0.2
      # contrast: 0.2
      # saturation: 0.2
  # - colormap

# 학습 설정
epochs: 3
batch_size: 5
optimizer: adamw
learning_rate: 0.0001
patience: 7
dropout_rate: 0.5

# 결과 저장 설정 
save_best_only: true
model_save_dir:
num_classes: 5
