# 실험 설정
experiment_id: verB_(seed_no)_(model_name)
backbone_name:  #ResNet50 MobileNetV2 DenseNet121 EfficientNetB0

# 데이터셋 설정
original_dataset_dir: /Volumes/PortableSSD/dataset-pepper
base_output_dir: /Users/vnlt/PROJECT/ex-cnn-cv/data/dataset
input_shape: [224, 224, 3]
train_ratio: 0.7 
val_ratio: 0.2 
test_ratio: 0.1
seed: 41 # test condition: full/41/236/7586
augmentations:
  #- color_jitter:
      # brightness: 0.2
      # contrast: 0.2
      # saturation: 0.2
  # - colormap

# 학습 설정
epochs: 30
batch_size: 15
optimizer: adamw #adam, adamw
learning_rate: 0.0001
weight_decay: 1e-5
patience: 10
dropout_rate: 0.5

# 결과 저장 설정 
save_best_only: true
model_save_dir: /Users/vnlt/PROJECT/ex-cnn-cv/models/save_models
num_classes: 5
